### ISSUE TITLE
A little more documentation?

### ISSUE THREAD

**Issue by mrobbetts** [dudest/node-red-contrib-soundweb#8]
I feel like I am missing something, as other people are figuring out how to use these blocks, but I am struggling! And I can't for the life of me find any working examples floating around.

Would it be possible for you to add some simple concrete examples for how to control DSP parameters?

# An example

I am trying to control the mute parameter for an audio channel on my BLU-326:
- This is on (output) card D of the BLU-326,
- This BLU-326 has Node Address of `0x4`, and is at `192.168.1.21`,
- In the Audio Architect UI, I see the HiQNet address of the card is `0x000403000004` (which makes sense when looking at the message format in the [document](https://bssaudio.com/en-US/site_elements/soundweb-london-third-party-control-application-guide) - I see that it includes the node address `0004`, the audio Virtual Address `03`, the card D Object address `000004`).
- In the venue explorer, I see that the Mute Parameter ID is `0x7D0`

This even looks like it makes sense, as all this together comes to exactly 8 bytes worth of address, and the address field in the Node-Red block's UI looks like a list of 8 values. So! 

## My first question

How to set this field? Like this?

<img width="500" alt="Screenshot 2024-02-21 at 23 23 11" src="https://github.com/dudest/node-red-contrib-soundweb/assets/1067896/0f06998a-3f5b-4f5c-8e3a-2a54028939b3">

I'm assuming not, because it doesn't work! 😉 

Or, perhaps it does? But that leads me to:

## My second question
What should the input messages look like for this block? For controlling a boolean parameter like Mute, should it be a simple boolean message? Or a number? A string?

And what on earth does the Topic field do? 😭 

## My Third question

Can we Get parameters/meters back out of a BSS device with this block? I'd love to be able to see gain settings, for example, that have been changed externally.

Are these things explained somewhere and I'm totally missing them?

**Comment by dudest** [comment]
Hello mrobbetts,

**disclamer:** I don't work for Harman and do this in my free time. I share this with the public freely; warts and all.

There are examples in the examples folder of this repository. I did just notice that the naming is inverted for the parameter presets and mute examples but you'll get the gist. I'll have to fix this on the next revision

# To answer your first question

The address field expects a buffer and there are limitations or quirks to buffer input fields in node red. In your screenshot you've entered HEX which will not be interpreted as such. You will have to enter the decimal value. If you click on the ... at the right, a buffer editor window will open up and so you can verify if your input is correct. 

Note that in Audio architect, if you add a third party controller and add some controls to it, you can see what your commands string will look like. You can toggle between hex and decimal, change delimiter, etc. *Be aware that the command it will show you includes byte substitution, that's why I've provided that information in the readme and the info pane of the nodes.*

# To answer your second question

A number. My implementation follows Harman's documentation as faithfully as possible.

The topic field is for... well... just that. Topic is a big part of MQTT and node-red. I suggest looking into the Node-red and MQTT documentation for answers. If you do set a topic in a *node-red-contrib-soundweb* node's properties, the information will not be sent to the BSS device but it will be added to feedback from the device.

# To answer your third question.

Yes, the *Soundweb-Control* node will send a subscribe message as soon as the server-node establishes a connection with a BSS device. Any changes done directly in audio architect or any other method will be published to any subscribers. You can even subscribe to a volume meter, but don't try to send any messages to it 🥲

**Comment by mrobbetts** [comment]
@dudest, thanks so much for your quick reply! You cleared everything up for me.

My mistake was tiny in the end: I _had_ actually even tried converting everything to decimal, but I'd left those two-digit numbers (like `00` and `04`) in place, instead of converting them to `0` and `4`; it turns out, that matters.

Now that I see it working as intended, I was able to answer my own questions from there.

Thanks again! I really appreciate the work you put into this module 😄
